/**
 * S01 — signature and encoding correctness.
 *
 * Three independent things are checked here:
 *  1. The published Aliyun fixed vector (GET) reproduces its documented
 *     signature exactly. This validates UTF-8 encoding, RFC 3986
 *     percent-encoding and HMAC-SHA1 end to end.
 *  2. The POST signatures match the original Go implementation
 *     (`internal/aliyun/client.go`) byte for byte, including special
 *     characters, a non-ASCII payload and an STS SecurityToken. The expected
 *     values were generated by running the Go source itself.
 *  3. The primitives' own published vectors (SHA-1, RFC 2202 HMAC-SHA1) hold.
 *
 * Why GET and POST are separate: the original Go client hardcodes the literal
 * `POST` into its StringToSign because it only ever issues POST form requests.
 * The official vector is a GET. A correct implementation must let the method
 * vary rather than copying that hardcoded assumption.
 */

import { test } from "node:test";
import assert from "node:assert/strict";

import {
  base64Decode,
  base64Encode,
  hexEncode,
  hmacSha1,
  percentEncode,
  sha1,
  utf8Bytes,
} from "../src/host/crypto.ts";
import {
  canonicalizedQueryString,
  formatRpcTimestamp,
  signParams,
  stringToSign,
} from "../src/providers/aliyun/signing.ts";

/** The published Aliyun example, used verbatim by the official docs. */
const OFFICIAL_VECTOR: Record<string, string> = {
  Action: "DescribeDedicatedHosts",
  AccessKeyId: "testid",
  RegionId: "cn-beijing",
  Version: "2014-05-26",
  Format: "JSON",
  SignatureMethod: "HMAC-SHA1",
  SignatureVersion: "1.0",
  Timestamp: "2023-03-13T08:34:30Z",
  SignatureNonce: "edb2b34af0af9a6d14deaf7c1a5315eb",
};

const OFFICIAL_SIGNATURE = "9NaGiOspFP5UPcwX8Iwt2YJXXuk=";

/* ------------------------------- primitives ------------------------------- */

test("sha1 matches published vectors", () => {
  assert.equal(
    hexEncode(sha1(utf8Bytes(""))),
    "da39a3ee5e6b4b0d3255bfef95601890afd80709",
  );
  assert.equal(
    hexEncode(sha1(utf8Bytes("abc"))),
    "a9993e364706816aba3e25717850c26c9cd0d89d",
  );
  // Multi-block input (> 64 bytes) exercises the block loop.
  assert.equal(
    hexEncode(sha1(utf8Bytes("abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq"))),
    "84983e441c3bd26ebaae4aa1f95129e5e54670f1",
  );
});

test("hmacSha1 matches RFC 2202 vectors", () => {
  const cases: Array<[string, string, string]> = [
    ["key", "The quick brown fox jumps over the lazy dog", "de7c9b85b8b78aa6bc8a7a36f70a90701c9db4d9"],
    ["Jefe", "what do ya want for nothing?", "effcdf6ae5eb2fa2d27416d5f184df9c259a7c79"],
    // 80-byte ASCII key: exercises the "hash the key first" branch.
    ["a".repeat(80), "Test With Truncation", "9f712b8f07b2516d9970eefe536729fa920e0c7c"],
  ];
  for (const [key, data, expected] of cases) {
    assert.equal(
      hexEncode(hmacSha1(utf8Bytes(key), utf8Bytes(data))),
      expected,
      `hmac-sha1 key=${key.slice(0, 12)}…`,
    );
  }

  // RFC 2202 case 6: an 80-byte key of raw 0xAA bytes. Note this cannot be
  // written as "\xaa".repeat(80) — that is code point U+00AA, which UTF-8
  // encodes to two bytes (0xC2 0xAA) and would test the wrong thing.
  assert.equal(
    hexEncode(
      hmacSha1(
        new Array<number>(80).fill(0xaa),
        utf8Bytes("Test Using Larger Than Block-Size Key - Hash Key First"),
      ),
    ),
    "aa4ae5e15272d00e95705637ce8a3b55ed402112",
  );
});

test("utf8Bytes handles BMP, surrogate pairs and lone surrogates", () => {
  assert.deepEqual(utf8Bytes("A"), [0x41]);
  assert.deepEqual(utf8Bytes("~"), [0x7e]);
  assert.deepEqual(utf8Bytes("中"), [0xe4, 0xb8, 0xad]);
  // U+1F600 GRINNING FACE as a surrogate pair.
  assert.deepEqual(utf8Bytes("😀"), [0xf0, 0x9f, 0x98, 0x80]);
  // A lone high surrogate is replaced, not silently truncated.
  assert.deepEqual(utf8Bytes("\ud83d"), [0xef, 0xbf, 0xbd]);
  assert.deepEqual(utf8Bytes("\udc00"), [0xef, 0xbf, 0xbd]);
});

test("base64 round-trips and rejects malformed input", () => {
  assert.equal(base64Encode([0x66, 0x6f, 0x6f]), "Zm9v");
  assert.equal(base64Encode([0x66, 0x6f]), "Zm8=");
  assert.equal(base64Encode([0x66]), "Zg==");
  assert.equal(base64Encode([]), "");
  for (const bytes of [[], [0], [1, 2], [1, 2, 3], [255, 0, 127, 128, 64]]) {
    assert.deepEqual(base64Decode(base64Encode(bytes)), bytes);
  }
  assert.equal(base64Decode("Zg"), null);
  assert.equal(base64Decode("Zg!!"), null);
});

/* ---------------------------- percent-encoding ---------------------------- */

test("percentEncode follows RFC 3986 rather than encodeURIComponent", () => {
  // Unreserved characters pass through, including '~'.
  assert.equal(
    percentEncode("AZaz09-_.~"),
    "AZaz09-_.~",
  );
  // The five characters encodeURIComponent would leave alone.
  assert.equal(percentEncode("!'()*"), "%21%27%28%29%2A");
  // Space becomes %20, never '+'.
  assert.equal(percentEncode("a b"), "a%20b");
  // Reserved delimiters are escaped.
  assert.equal(percentEncode("$&+,/:;=?@"), "%24%26%2B%2C%2F%3A%3B%3D%3F%40");
  // A literal percent sign must not be double-decoded later.
  assert.equal(percentEncode("a%2Fb"), "a%252Fb");
  // Non-ASCII becomes upper-case UTF-8 escapes.
  assert.equal(percentEncode("中文测试"), "%E4%B8%AD%E6%96%87%E6%B5%8B%E8%AF%95");
  assert.equal(percentEncode("😀"), "%F0%9F%98%80");
  // Hex escapes are upper-case, as the spec requires for comparison.
  assert.equal(percentEncode("\u00ff"), "%C3%BF");
});

/* ------------------------------ string to sign ---------------------------- */

test("canonical query string sorts keys and excludes Signature", () => {
  const canonical = canonicalizedQueryString({
    b: "2",
    a: "1",
    Signature: "ignored",
    "A b": "x y",
  });
  assert.equal(canonical, "A%20b=x%20y&a=1&b=2");
});

test("stringToSign uses the percent-encoded root path", () => {
  assert.equal(stringToSign("GET", "a=1"), "GET&%2F&a%3D1");
  assert.equal(stringToSign("post", "a=1"), "POST&%2F&a%3D1");
});

/* ------------------------------ fixed vectors ----------------------------- */

test("official Aliyun GET vector reproduces the documented signature", () => {
  assert.equal(
    signParams(OFFICIAL_VECTOR, "testsecret", "GET"),
    OFFICIAL_SIGNATURE,
  );
});

test("POST signatures match the original Go implementation", () => {
  // Values produced by running `sign()` in internal/aliyun/client.go.
  assert.equal(
    signParams(OFFICIAL_VECTOR, "testsecret", "POST"),
    "ZvQ9xGiFnquSJRvj+WE6kdSpTwU=",
    "GET and POST must not collapse to the same signature",
  );

  const special: Record<string, string> = {
    Action: "List Things",
    RegionId: "cn-hangzhou",
    Space: "a b",
    Chinese: "中文测试",
    Symbols: "+/~!*'()",
    Nested: "a%2Fb",
    Empty: "",
    Emoji: "😀",
    Reserved: "$&+,/:;=?@",
    Tilde: "~",
  };
  assert.equal(
    canonicalizedQueryString(special),
    "Action=List%20Things&Chinese=%E4%B8%AD%E6%96%87%E6%B5%8B%E8%AF%95&Emoji=%F0%9F%98%80&Empty=&Nested=a%252Fb&RegionId=cn-hangzhou&Reserved=%24%26%2B%2C%2F%3A%3B%3D%3F%40&Space=a%20b&Symbols=%2B%2F~%21%2A%27%28%29&Tilde=~",
  );
  assert.equal(
    signParams(special, "sec+ret&/=%@!", "POST"),
    "lh4rRyERUrYP5zbbD6NxYmy+OCg=",
  );

  // A SecurityToken is a signed parameter, not part of the signing key.
  assert.equal(
    signParams(
      {
        AccessKeyId: "STS.test",
        SecurityToken: "tok+/=en",
        Action: "QueryAccountBalance",
        Version: "2017-12-14",
      },
      "s3cr3t",
      "POST",
    ),
    "muswqJAJXEBqH5qNH+GbX8FTjRw=",
  );
});

test("signature changes when any signed input changes", () => {
  const base = signParams(OFFICIAL_VECTOR, "testsecret", "POST");
  const mutatedSecret = signParams(OFFICIAL_VECTOR, "testsecret2", "POST");
  const mutatedParam = signParams(
    { ...OFFICIAL_VECTOR, RegionId: "cn-shanghai" },
    "testsecret",
    "POST",
  );
  assert.notEqual(base, mutatedSecret);
  assert.notEqual(base, mutatedParam);
});

/* -------------------------------- timestamp ------------------------------- */

test("formatRpcTimestamp emits second-precision UTC with a literal Z", () => {
  assert.equal(
    formatRpcTimestamp(new Date("2023-03-13T08:34:30.123Z")),
    "2023-03-13T08:34:30Z",
  );
  assert.equal(
    formatRpcTimestamp(new Date("2026-01-02T03:04:05Z")),
    "2026-01-02T03:04:05Z",
  );
});
